sudo: false
language: node_js
node_js:
  - "5"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g codeclimate-test-reporter
  - npm install -g coveralls

script:
  - npm run test:cov

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
