language: node_js
sudo: false
node_js:
  - "4"
  - "5"
env:
  - CXX=g++-4.8
script: "npm run test:cov"
after_script: "npm run coveralls"
addons:
  code_climate:
    repo_token: 4ecb38703994e3a0f6526aba77ba6ba920974f078457493489a7d6290796b05a
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
