language: node_js
sudo: false
node_js:
  - "4"
  - "5"
env:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
