web:
  build: .
  environment:
    - TRANSMISSION_HOST=transmission
    - TRANSMISSION_PORT=9091
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_USER=kidibox
    - POSTGRES_PASSWORD=kidibox
  ports:
    - "3000:3000"
  links:
    - postgres
    - transmission
  volumes_from:
    - transmission
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=kidibox
    - POSTGRES_PASSWORD=kidibox
  ports:
    - "5432:5432"
transmission:
  image: dperson/transmission
  ports:
    - "9091:9091"
