CREATE TABLE "users" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL UNIQUE,
  "passwordHash" CHAR(192) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'NOW()',
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'NOW()'
);
